baseURL: http://localhost
title: freiheit.com
languageCode: en-us
defaultContentLanguage: en
relativeURLs: false
paginate: 10
enableRobotsTXT: true
disableKinds: ["taxonomy", "term"]
taxonomies:
  category: "categories"
  tag: "tags"