baseURL: http://localhost
title: freiheit.com
languageCode: en-us
defaultContentLanguage: en
relativeURLs: false
pagination.pagerSize: 10
enableRobotsTXT: true
taxonomies:
  category: "categories"
  tag: "tags"