de:
  title: 'freiheit.com - Building Large-Scale Software Since 1999'
  languageName: Deutsch
  weight: 1
en:
  title: 'freiheit.com - Building Large-Scale Software Since 1999'
  languageName: English
  weight: 2
pt:
  title: 'freiheit.com - Building Large-Scale Software Since 1999'
  languageName: Portugês
  weight: 3