de:
  title: 'freiheit.com - the next generation [DEUTSCH]'
  weight: 1
en:
  title: 'freiheit.com - the next generation [ENGLISH]'
  weight: 2
pt:
  title: 'freiheit.com - the next generation [PORTUGUÊS]'
  weight: 3