baseURL: https://freiheit.com
languageCode: en-us
title: freiheit.com
theme: freiheit-com
defaultContentLanguage: de
languages:
  de:
    title: 'freiheit.com - the next generation [DEUTSCH]'
  en:
    title: 'freiheit.com - the next generation [ENGLISH]'
  pt:
    title: 'freiheit.com - the next generation [PORTUGUÊS]'
