backend:
  name: github
local_backend: true
site_url: https://freiheit.com/freiheit-com-hugo/
# i18n: {structure: multiple_files, locales: [en, de, pt], default_locale: en}
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "what-others-say" # Used in routes, e.g., /admin/collections/blog
    label: "What others say" # Used in the UI
    folder: "content/what-others-say"
    media_folder: "/static/img/what-others-say"
    public_folder: "/img/what-others-say"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: "{{year}}-{{month}}-{{day}} - {{headline1}}"
    sortable_fields: ['date']
    fields: # The fields for each document, usually in front matter
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "First headline", name: "headline1", widget: "string"}
      - {label: "Second headline", name: "headline2", widget: "string", required: false}
      - {label: "Teaser text", name: "teaser", widget: "string"}
      - {label: "Lead Image", name: "lead_image", widget: "image", choose_url: false, allow_multiple: false, required: false}
      - {label: "Main Image", name: "image", widget: "image", choose_url: false, allow_multiple: false, required: false}
      - {label: "Vimeo ID", name: "vimeo", widget: "string", required: false}
      - {label: "Youtube ID", name: "youtube", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Hide header title", name: "hideHeaderTitle", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "what-weve-build"
    label: "Things we've build"
    folder: "content/what-weve-build"
    media_folder: "/static/img/what-weve-build"
    public_folder: "/img/what-weve-build"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{weight}} - {{title}}"
    sortable_fields: ['date', 'weight']
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", choose_url: false, allow_multiple: false}
      - {label: "Position", name: "weight", widget: "number", required: true}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Size", name: "size", widget: "select", options: ["small", "big"], default: "big"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
